name: Rust CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: debian-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - name: Build Backend
        run: |
          cd backend
          cargo build --release
      - name: Build Frontend
        run: |
          cd frontend
          cargo install trunk
          trunk build --release
